fix: fix Makefile HLS compiler flows
Update Makefile to automate HLS project
generation and error handling
improvements

- Add USE_VITIS variable to select vitis
(USE_VITIS=1 default) or vivado_hls
(USE_VITIS=0)
- add spdlog support for debug
- auto-generate Tcl script flow using
python (provide %.tcl rule fails numerous
hls components)
- must enumerate C and CXX hls target
files for Tcl support auto-gen flow and only
a subset of files are actually hls
components
- fix LD_LIBRARY_PATH and add to compile
command ( missing /usr/lib/x86_64-linux-gnu
- allow Makefile to process all targets
despite failing hls compile
- add clean target
- add .PRECIOUS: %.bin to allow debug of
.bin flow

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,10 +1,45 @@
-VHLS = $(shell vivado_hls -r)
+# This makefile was tested with Vivado HLS 2019.2
+# and Vitis v2024.1
+# 
+# setup_vitis_common /proj/xbuilds/2019.2_released
+# setup_vitis_common /proj/xbuilds/2024.1_released
+#
+
+# select the HLS compiler to use (vivado_hls or vitis)
+USE_VITIS=1
+
+ifeq ($(USE_VITIS),1)
+	VITIS_COMPILER = $(shell which vitis)
+	VHLS = $(VITIS_COMPILER)/../include
+	HLS_COMPILER=vitis-run --mode hls --tcl 
+else
+	VHLS = $(shell vivado_hls -r)
+	HLS_COMPILER=vivado_hls -f
+endif
+
 EXAMPLES = $(shell ls *-top.c)
 EXAMPLES_CPP = $(shell ls *-top.cpp)
 EXAMPLES_BIN = $(patsubst %.c,%,$(EXAMPLES))
 EXAMPLES_BIN += $(patsubst %.cpp,%,$(EXAMPLES_CPP))
 EXAMPLES_LOG = $(patsubst %.c,%.log,$(EXAMPLES))
 EXAMPLES_LOG += $(patsubst %.cpp,%.log,$(EXAMPLES_CPP))
+
+#CC = $(VHLS)/lnx64/tools/gcc/bin/gcc
+#CXX = $(VHLS)/lnx64/tools/gcc/bin/g++
+#CC = $(VHLS)/lnx64/tools/clang/bin/clang 
+#CXX = $(VHLS)/lnx64/tools/clang/bin/clang++
+#CC = gcc -I../../../spdlog/include -L../../../spdlog/build -lspdlog
+SPDLOG := -I../../../spdlog/include -L../../../spdlog/build -lspdlog
+CC = g++ $(SPDLOG)
+CXX = g++ $(SPDLOG)
+
+# insert new LD path to the LD_LIBRARY_PATH if it is not already there
+# 
+LD_PATH_NEW = /usr/lib/x86_64-linux-gnu
+LD_LIBRARY_PATH := $(shell echo $(value LD_LIBRARY_PATH) | grep -q $(LD_PATH_NEW) || echo $(LD_PATH_NEW):)$(value LD_LIBRARY_PATH)
+
+GEN_TCL = $(CURDIR)/../scripts/gen_vivado_hls_csynth_script.py
+HLS_CONFIG_FILE = $(CURDIR)/__hls_config__.ini
 
 $(warning $(EXAMPLES_LOG))
 
@@ -29,31 +64,96 @@ video_2dfilter_linebuffer_extended_constant-top.log: video_2dfilter_linebuffer_e
 	./$< $(INPUTFILE) video_2dfilter_linebuffer_extended_constant.bmp > $@
 
 %-top.bin: %-top.c %.c bitmap.c
-	gcc -I$(VHLS)/include -std=c99 $? -g -o $@
+	LD_LIBRARY_PATH=$(LD_LIBRARY_PATH) $(CC) -I$(VHLS)/include -std=c99 $? -g -o $@
 
 %-top.bin: %-top.cpp %.cpp
-	g++ -I$(VHLS)/include $? -g -o $@
+	LD_LIBRARY_PATH=$(LD_LIBRARY_PATH) $(CXX) -I$(VHLS)/include $? -g -o $@
 
 insertion_cell_sort-top.bin: insertion_cell_sort-top.cpp insertion_cell_sort.cpp insertion_sort.cpp
-	g++ -I$(VHLS)/include $? -g -o $@
+	echo $(LD_LIBRARY_PATH)
+	LD_LIBRARY_PATH=$(LD_LIBRARY_PATH) $(CXX) -I$(VHLS)/include $? -g -o $@
 
- #: %-top.bin
-%.tcl:
-	rm -f $@
-	echo "open_project $*.proj -reset" > $@
-	echo "add_file $*.c" >> $@
-	echo "add_file -tb $*-top.c" >> $@
-	echo "set_top $*" >> $@
-	echo "open_solution solution -reset" >> $@
-	echo "set_part virtex7" >> $@
-	echo "create_clock -period 5" >> $@
-	echo "csynth_design" >> $@
+#  missing cos_table and sin_table definition. No testbench files available
+#	dft.c \
+#	dft_precompute.c \
+
+CC_HLS_TARGET_FILES = \
+	block_fir.c \
+	fir.c \
+	fir11_initial.c \
+	fir_cslowed.c \
+	firrolled.c \
+	matrix_vector_base.c \
+	matrix_vector_base_unroll_inner.c \
+	matrix_vector_optimized.c \
+	matrix_vector_unroll_inner2.c \
+	video_2dfilter.c \
+	video_2dfilter_boundary_condition.c \
+	video_2dfilter_linebuffer.c \
+	video_2dfilter_linebuffer_extended.c \
+	video_2dfilter_linebuffer_extended_constant.c \
+	video_simple.c
+
+CXX_HLS_TARGET_FILES = \
+	block_mm.cpp \
+	complex_fir.cpp \
+	cordic.cpp \
+	cordic_fixed.cpp \
+	fft_stages.cpp \
+	fft_stages_loop.cpp \
+	fft_sw.cpp \
+	histogramSW.cpp \
+	histogram_dependence.cpp \
+	histogram_opt1.cpp \
+	huffman_encoding.cpp \
+	insertion_cell_sort.cpp \
+	insertion_sort.cpp \
+	insertion_sort_parallel.cpp \
+	insertion_sort_relaxed.cpp \
+	matrixmultiplication.cpp \
+	merge_sort.cpp \
+	merge_sort_loop_merged.cpp \
+	merge_sort_parallel.cpp \
+	merge_sort_restructured.cpp \
+	prefixsumBO.cpp \
+	prefixsumHW.cpp \
+	prefixsumSW.cpp \
+	prefixsum_optimized.cpp \
+	prefixsum_unrolled.cpp \
+	restructured_merge_sort.cpp \
+	spmv.cpp \
+	spmv_restructured.cpp \
+	spmv2.cpp \
+	spmv2_interleaved.cpp \
+	spmv2_restructured.cpp \
+	spmv_unrolled.cpp
+
+HLS_TARGETS = $(patsubst %.c,%.proj,$(CC_HLS_TARGET_FILES))
+HLS_TARGETS += $(patsubst %.cpp,%.proj,$(CXX_HLS_TARGET_FILES))
 
 %.proj: %.tcl
-	vivado_hls $?
+#	vivado_hls -f $?
+	$(HLS_COMPILER) $? || (echo "$(HLS_COMPILER) $? failed $$?"; exit 0)
+
+%.tcl: %.c
+	$(GEN_TCL) -c $(HLS_CONFIG_FILE) -i $< -o $@
+
+%.tcl: %.cpp
+	$(GEN_TCL) -c $(HLS_CONFIG_FILE) -i $< -o $@
 
 %.log: %.bin
-	./$< > $@
+	-./$< > $@ || (echo "./$< > $@ failed $$?"; exit 1)
+
+
+hls: $(HLS_TARGETS)
 
 test: $(EXAMPLES_LOG)
 
+
+clean:
+	rm -rf *.log *.bin *.tcl *.proj logs/* hls/*
+
+.PHONY: clean hls test
+
+# Prevent make from deleting the .bin intermediate files
+.PRECIOUS: %.bin
